name: 'MS Teams Notification'
description: 'GitHub Action to send a message to MS Teams with user mentions support'
author: 'anhdo9797'
inputs:
  TITLE:
    description: 'Title of the message'
    required: true
  BODY:
    description: 'Body of the message'
    required: true
  MS_TEAMS_WEBHOOK:  
    description: 'Microsoft Teams webhook URL for sending notifications'
    required: true
  MENTIONS:
    description: 'JSON array of users to mention. Each user object should have "id" (email) and "name" (display name) properties'
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: 'message-circle'  
  color: 'blue'