name: MS Teams Notification

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: anhdo9797/msteams-action@master
      with: 
        TITLE: "GitHub Action"
        BODY: "Success"
        MS_TEAMS_WEBHOOK: ${{ secrets.MSTEAMS_WEBHOOK }}
        MENTIONS: >
            [
              {"id": "baophan@tenomad.com", "name": "Bảo Phan"}
            ]
